[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK library"
documentation = "https://github.com/ebfull/bellman"
homepage = "https://github.com/ebfull/bellman"
license = "MIT/Apache-2.0"
name = "bellman"
repository = "https://github.com/ebfull/bellman"
version = "0.0.4"

[dependencies]
rand = "0.3"
bit-vec = "0.4.4"
futures = "0.1"
futures-cpupool = "0.1"
num_cpus = "1.6"
crossbeam = "0.3"

[dependencies.pairing]
git = "https://github.com/cryptape/pairing.git"
branch = "0.11-release"
default-features = false
features = ["unstable-wnaf"]

[features]
default = ["u128-support"]
u128-support = ["pairing/u128-support"]
